### ISSUE TITLE
请教：

### ISSUE THREAD

**Issue by Gijela** [omgcx1222/coderhub#1]
我没有使用过uniapp，冒昧问一下，uniapp项目是可以没有package.json的吗？还是说作者忘记上传该文件了？

**Comment by omgcx1222** [comment]
> 我没有使用过uniapp，冒昧问一下，uniapp项目是可以没有package.json的吗？还是说作者忘记上传该文件了？

我忘了有没有package.json，很久没写uniapp了。但是肯定是上传完整了的，不会特意忽略掉某个文件。
如果你是对聊天论坛这类项目感兴趣的话，建议看我的这个项目：[vue3 + ts + vant](https://github.com/omgcx1222/codehub)
